const $=id=>document.getElementById(id),FX=6.72;let activeSite='thehues',mode='actual',locked=false,S={};
const sites={thehues:{label:'TheHues',desc:'实际复盘以 Shopify 月净销售额为准；流量法与收入结构法使用同一净销售额口径做交叉校验。',note:'TH 默认期：2026 年 8 月（Asia/Shanghai）· Shopify 净销售额 $140,322.94 · 毛利、营销与固定支出仍为经营假设',driver:'Shopify + order_journey：新客直购 $103,492.04；90 天活跃小样池 310 人，15 人月内首次买正单；当月正单客户 186 人，其中普通老客 32 人。三类收入已按 Shopify 净销售额归一，互斥且合计 $140,322.94。',d:{sales:140322.94,sessions:86608,cvr:.3764086459,aov:430.43846626,directRevenue:103492.03623066,samplePool:310,sampleConv:4.8387096774,sampleAov:1002.14549502,oldPool:186,oldRepeat:17.2043010753,oldAov:681.210042,gross:60,marketing:42,fixed:300000}},kgorge:{label:'KGORGE',desc:'季节性站点：利润公式不变；不同月份更新销售驱动、毛利、营销费比和固定支出即可。',note:'默认销售额 $90,000 · 固定支出 ¥130,000 / 月',driver:'目前没有可靠的小样/老客池数据，默认保持 0。',d:{sales:90000,sessions:45967.31,cvr:.4769,aov:410.55,directRevenue:90000,samplePool:0,sampleConv:0,sampleAov:400,oldPool:0,oldRepeat:0,oldAov:410.55,gross:60,marketing:42,fixed:130000}},nicetown:{label:'NICETOWN',desc:'规模较小，但仍可使用同一套销售驱动与利润公式。',note:'默认销售额 $30,000 · 固定支出 ¥50,000 / 月',driver:'目前没有可靠的小样/老客池数据，默认保持 0。',d:{sales:30000,sessions:15322.44,cvr:.4769,aov:410.55,directRevenue:30000,samplePool:0,sampleConv:0,sampleAov:400,oldPool:0,oldRepeat:0,oldAov:410.55,gross:60,marketing:42,fixed:50000}}};
const defs={sales:['salesN','salesR',0,1e6],sessions:['sessionsN','sessionsR',0,1e6],cvr:['cvrN','cvrR',0,10],aov:['aovN','aovR',0,2000],directRevenue:['directRevenueN','directRevenueR',0,1e6],samplePool:['samplePoolN','samplePoolR',0,1e5],sampleConv:['sampleConvN','sampleConvR',0,100],sampleAov:['sampleAovN','sampleAovR',0,2000],oldPool:['oldPoolN','oldPoolR',0,1e6],oldRepeat:['oldRepeatN','oldRepeatR',0,100],oldAov:['oldAovN','oldAovR',0,2000],gross:['grossN','grossR',0,100],marketing:['marketingN','marketingR',0,100],fixed:['fixedN','fixedR',0,2e6]};
const state=Object.fromEntries(Object.entries(sites).map(([k,v])=>[k,{...v.d,manualSales:v.d.sales,mode:'actual'}]));let D={...state.thehues};
const clamp=(v,a,b)=>Math.min(b,Math.max(a,v)),usd=v=>(v<0?'-':'')+'$'+Math.abs(v).toLocaleString('en-US',{maximumFractionDigits:0}),rmb=v=>(v<0?'-':'')+'¥'+Math.abs(v).toLocaleString('zh-CN',{maximumFractionDigits:0}),pct=v=>Number.isFinite(v)?v.toFixed(1)+'%':'—',short=v=>'$'+(v>=1000?(v/1000).toFixed(v>=100000?0:1)+'k':Math.round(v));
function setVal(k,v){const d=defs[k];v=clamp(Number(v)||0,d[2],d[3]);D[k]=v;const n=$(d[0]),r=d[1]?$(d[1]):null;if(n){if(['cvr','sampleConv','oldRepeat'].includes(k))n.value=v.toFixed(4);else if(['aov','sampleAov','oldAov','directRevenue'].includes(k))n.value=v.toFixed(2);else if(['gross','marketing'].includes(k))n.value=Number.isInteger(v)?v:v.toFixed(1);else n.value=Number.isInteger(v)?v:v.toFixed(2)}if(r)r.value=clamp(v,+r.min,+r.max)}
function applyD(){Object.keys(defs).forEach(k=>setVal(k,D[k]??0))}
function save(){state[activeSite]={...D,mode,manualSales:state[activeSite].manualSales??D.sales}}
function forecast(){const traffic=D.sessions*(D.cvr/100)*D.aov,direct=D.directRevenue,sample=D.samplePool*(D.sampleConv/100)*D.sampleAov,old=D.oldPool*(D.oldRepeat/100)*D.oldAov,structure=direct+sample+old;return{traffic,direct,sample,old,structure}}
function loadSite(k){if(k===activeSite)return;save();activeSite=k;D={...state[k]};mode=D.mode||'actual';if(mode==='actual')D.sales=D.manualSales??D.sales;applyD();header();calc()}
function header(){const s=sites[activeSite];$('pageTitle').textContent=s.label+' 单月经营模型';$('pageDesc').textContent=s.desc;$('siteNote').textContent=s.note;$('driverNote').textContent=s.driver;document.querySelectorAll('.site-btn').forEach(b=>b.classList.toggle('active',b.dataset.site===activeSite))}
function backsolveTraffic(target){const den=(D.cvr/100)*D.aov;if(den>0)setVal('sessions',target/den)}
function backsolveStructure(target){const f=forecast(),total=f.structure;if(total>0){const ratio=target/total;setVal('directRevenue',D.directRevenue*ratio);setVal('samplePool',D.samplePool*ratio);setVal('oldPool',D.oldPool*ratio)}else setVal('directRevenue',target)}
function renderMode(){
 const actual=mode==='actual',traffic=mode==='traffic',structure=mode==='structure';
 $('actualModeBtn').classList.toggle('active',actual);$('trafficModeBtn').classList.toggle('active',traffic);$('structureModeBtn').classList.toggle('active',structure);
 $('salesN').disabled=false;$('salesR').disabled=false;$('salesBadge').classList.toggle('active',!actual);$('salesMain').classList.toggle('mode-linked',!actual);
 $('trafficMethodCard').classList.toggle('active-method',traffic);$('structureMethodCard').classList.toggle('active-method',structure);
 $('salesLabel').textContent=actual?'月净销售额':traffic?'流量法 · 预测净销售额':'收入结构法 · 预测净销售额';
 $('salesBadge').textContent=actual?'利润基数：实际销售额':traffic?'利润基数：流量法预测销售额':'利润基数：收入结构法预测销售额';
 $('salesHelper').textContent=actual?'实际模式下直接使用 Shopify 月净销售额。':traffic?'双向联动：拖动这里的净销售额会在保持购买会话 CVR / 净收入不变时反推 Sessions；修改任一流量参数也会实时更新净销售额。':'双向联动：拖动这里的净销售额会按当前三类收入占比同步缩放；修改任一结构参数也会实时更新净销售额。';
 $('modeHint').textContent=actual?'两套预测只用于交叉校验，不会加到实际销售额。':traffic?'利润仅使用流量法预测净销售额；Sessions / CVR / 购买会话净收入采用同一 Shopify 口径。':'利润仅使用收入结构法预测净销售额；新客直购、小样首转与普通老客复购互斥。';
 $('driverStatus').textContent=actual?'实际销售额参与利润':traffic?'流量法参与利润':'结构法参与利润';$('driverStatus').classList.toggle('active',!actual)
}
function switchMode(m){if(m===mode)return;if(m!=='actual'&&mode==='actual')state[activeSite].manualSales=D.sales;mode=m;if(mode==='actual'){D.sales=state[activeSite].manualSales??sites[activeSite].d.sales;setVal('sales',D.sales)}else $('driverDetails').open=true;calc()}
function calc(source){if(locked)return;locked=true;
 if(source==='sales'){
   if(mode==='actual')state[activeSite].manualSales=D.sales;
   else if(mode==='traffic')backsolveTraffic(D.sales);
   else if(mode==='structure')backsolveStructure(D.sales);
 }
 const f=forecast();
 if(mode==='traffic')setVal('sales',f.traffic);else if(mode==='structure')setVal('sales',f.structure);
 const rev=D.sales*FX,g=D.gross/100,m=D.marketing/100,profit=rev*g-rev*m-D.fixed,margin=rev?profit/rev:0,spread=g-m,beSales=spread>0?D.fixed/spread/FX:Infinity,beM=g-(rev?D.fixed/rev:0);S={rev,g,m,profit,margin,beSales,beM,f};state[activeSite]={...D,mode,manualSales:state[activeSite].manualSales??D.sales};render();renderMode();locked=false}
function render(){const s=S,f=s.f,diff=f.structure-f.traffic,diffPct=f.traffic?diff/f.traffic*100:0;$('directRevenueOut').textContent=usd(f.direct);$('sampleRevenueOut').textContent=usd(f.sample);$('oldRevenueOut').textContent=usd(f.old);$('trafficSalesOut').textContent=usd(f.traffic);$('structureSalesOut').textContent=usd(f.structure);$('trafficSummaryOut').textContent=usd(f.traffic);$('structureSummaryOut').textContent=usd(f.structure);$('forecastDiffOut').textContent=(diff>=0?'+':'-')+usd(Math.abs(diff));$('forecastDiffPctOut').textContent=(diffPct>=0?'+':'')+pct(diffPct);$('salesRmbSmall').textContent='≈ '+rmb(s.rev);$('profitOut').textContent=rmb(s.profit);$('profitUsdOut').textContent='≈ '+usd(s.profit/FX);$('marginOut').textContent=pct(s.margin*100);$('beSalesOut').textContent=Number.isFinite(s.beSales)?short(s.beSales):'不可达';$('beMarketingOut').textContent=pct(s.beM*100);$('profitOut').className='v '+(s.profit>=0?'positive':'negative');$('marginOut').className='v '+(s.margin>=0?'positive':'negative');const st=$('status');st.style.background=s.profit>=0?'var(--goodbg)':'var(--badbg)';st.style.color=s.profit>=0?'var(--good)':'var(--bad)';st.textContent=s.profit>=0?'当前单月盈利 '+rmb(s.profit)+'。':'当前单月亏损 '+rmb(Math.abs(s.profit))+'；按当前结构，盈亏平衡销售额约 '+(Number.isFinite(s.beSales)?short(s.beSales):'不可达')+'。';$('flowGross').textContent='$'+(s.g*100).toFixed(0);$('flowAfterMkt').textContent='$'+((s.g-s.m)*100).toFixed(1);$('flowFinal').textContent=(s.margin>=0?'$':'-$')+Math.abs(s.margin*100).toFixed(1);$('flowFinalBox').className='step '+(s.margin>=0?'good':'bad');$('grossProfitOut').textContent=rmb(s.rev*s.g);$('marketingAmtOut').textContent=rmb(s.rev*s.m);$('chartMeta').textContent='毛利 '+pct(s.g*100)+' · 营销 '+pct(s.m*100)+' · 固定 '+rmb(D.fixed);drawChart()}
function marginAt(sales){return sales>0?S.g-S.m-D.fixed/(sales*FX):0}
function drawChart(){const c=$('chart'),b=c.getBoundingClientRect(),dpr=devicePixelRatio||1,w=b.width,h=b.height;c.width=Math.round(w*dpr);c.height=Math.round(h*dpr);const x=c.getContext('2d');x.setTransform(dpr,0,0,dpr,0,0);const p={l:48,r:14,t:18,b:30},xmin=20000,xmax=Math.max(500000,D.sales*1.45,Number.isFinite(S.beSales)?S.beSales*1.25:0),pts=[];for(let i=0;i<=120;i++){const g=xmin+(xmax-xmin)*i/120;pts.push({g,y:marginAt(g)*100})}const ymin=Math.min(-40,Math.floor(Math.min(...pts.map(v=>v.y))/10)*10),ymax=Math.max(25,Math.ceil(Math.max(...pts.map(v=>v.y))/10)*10),iw=w-p.l-p.r,ih=h-p.t-p.b,X=g=>p.l+(g-xmin)/(xmax-xmin)*iw,Y=y=>p.t+(ymax-y)/(ymax-ymin)*ih;x.clearRect(0,0,w,h);x.font='11px -apple-system,system-ui';x.fillStyle='#98a2b3';x.strokeStyle='#eaecf0';x.lineWidth=1;for(let y=Math.ceil(ymin/10)*10;y<=ymax;y+=10){const py=Y(y);x.beginPath();x.moveTo(p.l,py);x.lineTo(w-p.r,py);x.stroke();x.fillText(y+'%',4,py+4)}for(let i=0;i<=4;i++){const g=xmin+(xmax-xmin)*i/4;x.fillText(short(g),Math.max(2,X(g)-16),h-8)}if(ymin<0&&ymax>0){x.strokeStyle='#98a2b3';x.beginPath();x.moveTo(p.l,Y(0));x.lineTo(w-p.r,Y(0));x.stroke()}if(Number.isFinite(S.beSales)&&S.beSales>=xmin&&S.beSales<=xmax){const bx=X(S.beSales);x.save();x.setLineDash([5,5]);x.strokeStyle='#98a2b3';x.beginPath();x.moveTo(bx,p.t);x.lineTo(bx,h-p.b);x.stroke();x.restore();x.fillStyle='#667085';x.fillText('盈亏平衡 '+short(S.beSales),Math.min(w-110,bx+6),p.t+12)}x.strokeStyle='#111827';x.lineWidth=2.8;x.beginPath();pts.forEach((v,i)=>i?x.lineTo(X(v.g),Y(v.y)):x.moveTo(X(v.g),Y(v.y)));x.stroke();if(D.sales>=xmin){const cy=marginAt(D.sales)*100;x.fillStyle=cy>=0?'#067647':'#b42318';x.beginPath();x.arc(X(D.sales),Y(cy),5.5,0,Math.PI*2);x.fill();x.fillStyle='#344054';x.fillText('当前 '+short(D.sales),Math.min(w-90,X(D.sales)+8),Math.max(18,Y(cy)-8))}c._map={p,w,h,xmin,xmax,X,Y}}
function inspect(e){const c=$('chart'),m=c._map;if(!m)return;const r=c.getBoundingClientRect(),cx=e.clientX-r.left;if(cx<m.p.l||cx>m.w-m.p.r){$('tip').style.display='none';return}const g=m.xmin+(cx-m.p.l)/(m.w-m.p.l-m.p.r)*(m.xmax-m.xmin),y=marginAt(g)*100,t=$('tip');t.innerHTML='净销售额 <b>'+short(g)+'</b><br>经营利润率 <b>'+pct(y)+'</b>';t.style.display='block';t.style.left=Math.min(m.w-118,Math.max(2,cx+7))+'px';t.style.top=Math.max(2,Math.min(m.h-45,m.Y(y)-21))+'px'}
Object.keys(defs).forEach(k=>{const n=$(defs[k][0]),r=defs[k][1]?$(defs[k][1]):null;n.addEventListener('input',()=>{setVal(k,n.value);calc(k==='sales'?'sales':'input')});if(r)r.addEventListener('input',()=>{setVal(k,r.value);calc(k==='sales'?'sales':'input')})});document.querySelectorAll('.site-btn').forEach(b=>b.onclick=()=>loadSite(b.dataset.site));$('actualModeBtn').onclick=()=>switchMode('actual');$('trafficModeBtn').onclick=()=>switchMode('traffic');$('structureModeBtn').onclick=()=>switchMode('structure');$('resetBtn').onclick=()=>{const d=sites[activeSite].d;state[activeSite]={...d,manualSales:d.sales,mode:'actual'};D={...state[activeSite]};mode='actual';applyD();header();calc()};$('chart').addEventListener('pointermove',inspect);$('chart').addEventListener('pointerleave',()=>$('tip').style.display='none');addEventListener('resize',drawChart);applyD();header();calc();
